"""
Whole-brain calcium trace analysis — preliminary dataset.

For each animal: per-frame fluid ROI = top TOP_PERCENT% of pixels in each
frame's max-intensity projection. Saves per-animal results under
outputs/cache/{animal}.npz so re-runs only compute new animals. Drops the
first BLEACH_CUTOFF_FRAME frames for stats and compares BlaC vs
BlaC-Catalytically Dead with Mann-Whitney on post-bleach raw mean.

QC videos are generated by the separate make_qc_videos.py script.

Analysis is byte-identical to analyze_calcium_traces_finaldata.py; only the
data-source path and the animal-to-condition mapping at the top differ.
"""

import hashlib
import json
from datetime import date
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import zarr
from scipy.stats import mannwhitneyu, sem
from skimage.segmentation import find_boundaries

# ── Configuration ──────────────────────────────────────────────────────────────

PREPROCESSED_DIR = Path(
    "/store1/lauren/Tetramisole_Immobilized_Imaging/"
    "2026_cAMP_wholebrain_with_pdfr1_BlaC_Immobilized/PreliminaryData/pre-processed"
)

# Outputs (plots / CSVs / stats / snapshots) go to a date-stamped sibling of
# PREPROCESSED_DIR so previous runs aren't overwritten.
TODAY = date.today().strftime("%Y%m%d")
OUTPUT_DIR = PREPROCESSED_DIR.parent / f"{TODAY}_output"

# Cache is kept at a stable (non-date-stamped) sibling of PREPROCESSED_DIR
# so future-day re-runs reuse already-computed animals instead of recomputing.
CACHE_DIR = PREPROCESSED_DIR.parent / "cache"
FRAME_RATE_HZ = 1.7
N_FRAMES = 800
BLEACH_CUTOFF_FRAME = 50

CALCIUM_CHANNEL = 0
TOP_PERCENT = 5
CACHE_VERSION = 1
MASK_SNAPSHOT_FRAMES = [50, 400, 799]

# Condition mapping — preliminary dataset uses explicit per-animal lists
BLAC_CAT_DEAD = ["2026-03-03-01", "2026-03-03-02", "2026-03-03-03", "2026-03-03-04"]
BLAC = ["2026-03-03-05", "2026-03-04-02", "2026-03-04-03", "2026-03-04-04", "2026-03-04-05"]

# Animals to exclude from analysis (e.g. bad data)
EXCLUDE = ["2026-03-03-04"]

COLOR_DEAD = "#4477AA"
COLOR_ALIVE = "#CC3311"

# Build ANIMALS list (same downstream variables as finaldata.py)
blac_cat_dead = [n for n in BLAC_CAT_DEAD if n not in EXCLUDE]
blac = [n for n in BLAC if n not in EXCLUDE]
all_names = blac_cat_dead + blac
animal_condition = {n: "BlaC-Cat.Dead" for n in blac_cat_dead}
animal_condition.update({n: "BlaC" for n in blac})
animal_dir = {n: PREPROCESSED_DIR for n in all_names}
ANIMALS = [{"name": n, "condition": animal_condition[n], "dir": animal_dir[n]}
           for n in all_names]

# ── Helper functions ───────────────────────────────────────────────────────────

def open_zarr(name: str, preprocessed_dir: Path):
    path = str(preprocessed_dir / f"{name}.zarr")
    return zarr.open(path, mode="r")


def compute_mip(arr, t: int, channel: int) -> np.ndarray:
    vol = np.asarray(arr[t, channel])
    return vol.max(axis=0).astype(np.float32)


def extract_trace_fluid(arr, channel: int, n_top: int):
    """
    Per-frame fluid mask: top-n_top brightest pixels in each frame's MIP.

    Returns:
        mean_trace (n_t,), sum_trace (n_t,),
        avg_mip (Y, X) — mean MIP across all frames,
        mask_freq (Y, X) — count of frames each pixel was in the top-N,
        snapshots dict {frame_index: {"mip": (Y, X) float32,
                                      "mask": (Y, X) bool}}.
    """
    n_t = arr.shape[0]
    Y, X = arr.shape[3], arr.shape[4]

    mean_trace = np.zeros(n_t, dtype=np.float64)
    sum_trace = np.zeros(n_t, dtype=np.float64)
    mip_accum = np.zeros((Y, X), dtype=np.float64)
    mask_freq = np.zeros((Y, X), dtype=np.int64)
    snapshots = {}

    snapshot_set = set(MASK_SNAPSHOT_FRAMES)

    for t in range(n_t):
        mip = compute_mip(arr, t, channel)
        flat = mip.ravel()
        idx = np.argpartition(flat, -n_top)[-n_top:]
        vals = flat[idx]

        mean_trace[t] = vals.mean()
        sum_trace[t] = vals.sum()
        mip_accum += mip
        mask_freq.ravel()[idx] += 1

        if t in snapshot_set:
            mask = np.zeros((Y, X), dtype=bool)
            mask.ravel()[idx] = True
            snapshots[t] = {"mip": mip.astype(np.float32), "mask": mask}

        if (t + 1) % 200 == 0:
            print(f"    Frame {t + 1}/{n_t}")

    avg_mip = (mip_accum / n_t).astype(np.float32)
    return mean_trace, sum_trace, avg_mip, mask_freq, snapshots


# ── Per-animal results cache ───────────────────────────────────────────────────

def cache_params(n_top_pixels: int) -> dict:
    return {
        "version": CACHE_VERSION,
        "channel": CALCIUM_CHANNEL,
        "top_percent": TOP_PERCENT,
        "n_top_pixels": int(n_top_pixels),
        "n_frames": int(N_FRAMES),
        "bleach_cutoff": int(BLEACH_CUTOFF_FRAME),
        "snapshot_frames": list(MASK_SNAPSHOT_FRAMES),
    }


def cache_hash(params: dict) -> str:
    return hashlib.sha1(json.dumps(params, sort_keys=True).encode()).hexdigest()[:12]


def cache_path(name: str) -> Path:
    return CACHE_DIR / f"{name}.npz"


def load_cache(name: str, params: dict):
    p = cache_path(name)
    if not p.exists():
        return None
    data = np.load(p, allow_pickle=True)
    if str(data["params_hash"]) != cache_hash(params):
        return None
    return data


def save_cache(name, params, mean_trace, sum_trace, avg_mip, mask_freq, snapshots):
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    snap_data = {}
    for t, d in snapshots.items():
        snap_data[f"snap_mip_{t}"] = d["mip"]
        snap_data[f"snap_mask_{t}"] = d["mask"]
    np.savez_compressed(
        cache_path(name),
        params_hash=cache_hash(params),
        params_json=json.dumps(params, sort_keys=True),
        mean_trace=mean_trace,
        sum_trace=sum_trace,
        avg_mip=avg_mip,
        mask_freq=mask_freq,
        snapshot_frames=np.array(sorted(snapshots.keys())),
        **snap_data,
    )


# ── Main execution ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    for subdir in ["traces", "plots", "plots/snapshots", "stats"]:
        (OUTPUT_DIR / subdir).mkdir(parents=True, exist_ok=True)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    print(f"  Output dir: {OUTPUT_DIR}")
    print(f"  Cache dir:  {CACHE_DIR}")

    time_s = np.arange(N_FRAMES) / FRAME_RATE_HZ
    print(f"  Total animals: {len(all_names)} ({len(blac_cat_dead)} Dead, {len(blac)} BlaC)")
    print(f"  Frames: {N_FRAMES}, Bleach cutoff: frame {BLEACH_CUTOFF_FRAME}")
    if EXCLUDE:
        print(f"  Excluding: {EXCLUDE}")

    # ── Step 0: Validate that every animal shares the same (Y, X) shape ────
    print("\n" + "=" * 60)
    print("  STEP 0: Validate image dimensions")
    print("=" * 60)
    shapes = {n: open_zarr(n, animal_dir[n]).shape[-2:] for n in all_names}
    unique_shapes = set(shapes.values())
    if len(unique_shapes) != 1:
        raise ValueError(
            f"Animals have inconsistent (Y, X) shapes: {shapes}. "
            f"Fluid ROI requires all animals share the same image size."
        )
    Y, X = unique_shapes.pop()
    N_TOP_PIXELS = int(np.ceil(TOP_PERCENT / 100.0 * Y * X))
    print(f"  Image (Y, X) = ({Y}, {X}); fluid ROI = top {N_TOP_PIXELS} pixels "
          f"per frame ({TOP_PERCENT}%)")

    # ── Step 1: Extract traces (with cache) ────────────────────────────────
    print("\n" + "=" * 60)
    print("  STEP 1: Extract calcium traces")
    print("=" * 60)

    traces_mean = {}
    traces_sum = {}
    avg_mips = {}
    mask_freqs = {}
    snapshots_by_animal = {}

    params = cache_params(N_TOP_PIXELS)
    for name in all_names:
        cond = animal_condition[name]
        cached = load_cache(name, params)
        if cached is not None:
            print(f"  {name} ({cond}): cache hit")
            traces_mean[name] = cached["mean_trace"]
            traces_sum[name] = cached["sum_trace"]
            avg_mips[name] = cached["avg_mip"]
            mask_freqs[name] = cached["mask_freq"]
            snapshots_by_animal[name] = {
                int(t): {
                    "mip": cached[f"snap_mip_{int(t)}"],
                    "mask": cached[f"snap_mask_{int(t)}"],
                }
                for t in cached["snapshot_frames"]
            }
            continue

        print(f"\n  {name} ({cond}): computing")
        arr = open_zarr(name, animal_dir[name])
        print(f"    Shape: {arr.shape}")
        mean_t, sum_t, avg_mip, mask_freq, snaps = extract_trace_fluid(
            arr, CALCIUM_CHANNEL, N_TOP_PIXELS
        )
        save_cache(name, params, mean_t, sum_t, avg_mip, mask_freq, snaps)
        traces_mean[name] = mean_t
        traces_sum[name] = sum_t
        avg_mips[name] = avg_mip
        mask_freqs[name] = mask_freq
        snapshots_by_animal[name] = snaps
        print(f"    Mean intensity: [{mean_t.min():.1f}, {mean_t.max():.1f}]")

    # ── Step 2: QC — mask-frequency heatmap per animal ─────────────────────
    print("\n" + "=" * 60)
    print("  STEP 2: QC — mask-frequency heatmaps")
    print("=" * 60)

    n_animals = len(all_names)
    ncols = min(5, n_animals)
    nrows = (n_animals + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(4 * ncols, 4 * nrows))
    axes = np.atleast_2d(axes)

    for idx, name in enumerate(all_names):
        row, col = divmod(idx, ncols)
        ax = axes[row, col]
        avg_mip = avg_mips[name]
        ax.imshow(avg_mip, cmap="gray",
                  vmin=np.percentile(avg_mip, 1),
                  vmax=np.percentile(avg_mip, 99.5))
        freq = mask_freqs[name] / N_FRAMES
        ax.imshow(np.ma.masked_where(freq < 0.01, freq),
                  cmap="autumn", vmin=0.0, vmax=1.0, alpha=0.6)
        cond = animal_condition[name]
        ax.set_title(f"{name}\n({cond})", fontsize=8)
        ax.axis("off")

    for idx in range(n_animals, nrows * ncols):
        row, col = divmod(idx, ncols)
        axes[row, col].axis("off")

    plt.suptitle("Fluid mask frequency (orange = fraction of frames in top-N) on avg-MIP",
                 fontsize=12)
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "plots" / "mask_frequency.png",
                dpi=150, bbox_inches="tight")
    plt.close()
    print("  Saved mask_frequency.png")

    # ── Step 3: QC — snapshot frames per animal ────────────────────────────
    print("\n" + "=" * 60)
    print("  STEP 3: QC — mask snapshots at frames 50/400/799")
    print("=" * 60)

    for name in all_names:
        fig, axes = plt.subplots(1, len(MASK_SNAPSHOT_FRAMES),
                                 figsize=(5 * len(MASK_SNAPSHOT_FRAMES), 5))
        for ax, t in zip(np.atleast_1d(axes), MASK_SNAPSHOT_FRAMES):
            snap = snapshots_by_animal[name][int(t)]
            mip = snap["mip"]
            mask = snap["mask"]
            p1, p99 = np.percentile(mip, [0.5, 99.5])
            ax.imshow(mip, cmap="gray", vmin=p1, vmax=p99)
            outline = find_boundaries(mask, mode="thick")
            overlay = np.zeros((*mip.shape, 4))
            overlay[outline] = [0, 1, 0, 0.9]
            ax.imshow(overlay)
            ax.set_title(f"Frame {t}")
            ax.axis("off")
        fig.suptitle(f"{name} — fluid mask snapshots ({animal_condition[name]})",
                     fontsize=11)
        plt.tight_layout()
        plt.savefig(OUTPUT_DIR / "plots" / "snapshots" / f"snapshots_{name}.png",
                    dpi=120, bbox_inches="tight")
        plt.close()
    print(f"  Saved {n_animals} snapshot PNGs to plots/snapshots/")

    # ── Step 4: Save raw trace CSVs ────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  STEP 4: Save trace data")
    print("=" * 60)

    raw_data = {"time_s": time_s}
    for name in all_names:
        raw_data[f"{name}_mean"] = traces_mean[name]
        raw_data[f"{name}_sum"] = traces_sum[name]
    pd.DataFrame(raw_data).to_csv(OUTPUT_DIR / "traces" / "raw_traces.csv", index=False)
    print("  Saved raw_traces.csv")

    # ── Step 5: Plot raw traces (full + post-bleach) ──────────────────────
    print("\n" + "=" * 60)
    print("  STEP 5: Plotting raw traces")
    print("=" * 60)

    time_post = time_s[BLEACH_CUTOFF_FRAME:]

    for metric_name, raw_traces in [("mean", traces_mean), ("sum", traces_sum)]:
        dead_group = np.array([raw_traces[n] for n in blac_cat_dead])
        alive_group = np.array([raw_traces[n] for n in blac])

        fig, ax = plt.subplots(figsize=(12, 5))
        for name in blac_cat_dead:
            ax.plot(time_s, raw_traces[name], color=COLOR_DEAD, alpha=0.3, linewidth=0.8)
        for name in blac:
            ax.plot(time_s, raw_traces[name], color=COLOR_ALIVE, alpha=0.3, linewidth=0.8)
        ax.plot(time_s, dead_group.mean(axis=0), color=COLOR_DEAD, linewidth=2.5,
                label="BlaC-Cat.Dead")
        ax.plot(time_s, alive_group.mean(axis=0), color=COLOR_ALIVE, linewidth=2.5,
                label="BlaC")
        ax.axvline(time_s[BLEACH_CUTOFF_FRAME], color="orange", linestyle=":", linewidth=1.5,
                   label=f"Bleach cutoff (frame {BLEACH_CUTOFF_FRAME})")
        ax.set_xlabel("Time (s)")
        ax.set_ylabel(f"{metric_name.capitalize()} intensity")
        ax.set_title(f"Raw {metric_name.capitalize()} Intensity Traces")
        ax.legend()
        plt.tight_layout()
        plt.savefig(OUTPUT_DIR / "plots" / f"raw_traces_{metric_name}.png",
                    dpi=150, bbox_inches="tight")
        plt.close()

        fig, ax = plt.subplots(figsize=(12, 5))
        for name in blac_cat_dead:
            ax.plot(time_post, raw_traces[name][BLEACH_CUTOFF_FRAME:],
                    color=COLOR_DEAD, alpha=0.3, linewidth=0.8)
        for name in blac:
            ax.plot(time_post, raw_traces[name][BLEACH_CUTOFF_FRAME:],
                    color=COLOR_ALIVE, alpha=0.3, linewidth=0.8)
        ax.plot(time_post, dead_group.mean(axis=0)[BLEACH_CUTOFF_FRAME:],
                color=COLOR_DEAD, linewidth=2.5, label="BlaC-Cat.Dead")
        ax.plot(time_post, alive_group.mean(axis=0)[BLEACH_CUTOFF_FRAME:],
                color=COLOR_ALIVE, linewidth=2.5, label="BlaC")
        ax.set_xlabel("Time (s)")
        ax.set_ylabel(f"{metric_name.capitalize()} intensity")
        ax.set_title(f"Raw {metric_name.capitalize()} — Post-Bleach (frame {BLEACH_CUTOFF_FRAME}+)")
        ax.legend()
        plt.tight_layout()
        plt.savefig(OUTPUT_DIR / "plots" / f"raw_traces_{metric_name}_post_bleach.png",
                    dpi=150, bbox_inches="tight")
        plt.close()

        fig, ax = plt.subplots(figsize=(12, 5))
        dead_m = dead_group.mean(axis=0)[BLEACH_CUTOFF_FRAME:]
        dead_se = sem(dead_group, axis=0)[BLEACH_CUTOFF_FRAME:]
        alive_m = alive_group.mean(axis=0)[BLEACH_CUTOFF_FRAME:]
        alive_se = sem(alive_group, axis=0)[BLEACH_CUTOFF_FRAME:]

        ax.plot(time_post, dead_m, color=COLOR_DEAD, linewidth=2, label="BlaC-Cat.Dead")
        ax.fill_between(time_post, dead_m - dead_se, dead_m + dead_se,
                        color=COLOR_DEAD, alpha=0.2)
        ax.plot(time_post, alive_m, color=COLOR_ALIVE, linewidth=2, label="BlaC")
        ax.fill_between(time_post, alive_m - alive_se, alive_m + alive_se,
                        color=COLOR_ALIVE, alpha=0.2)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel(f"Raw {metric_name} intensity")
        ax.set_title(f"BlaC vs BlaC-Cat.Dead — Raw {metric_name.capitalize()} ± SEM Post-Bleach")
        ax.legend()
        plt.tight_layout()
        plt.savefig(OUTPUT_DIR / "plots" / f"comparison_{metric_name}_sem.png",
                    dpi=150, bbox_inches="tight")
        plt.close()

    print("  Saved all trace plots")

    # ── Step 6: Post-bleach raw statistics ─────────────────────────────────
    print("\n" + "=" * 60)
    print("  STEP 6: Post-bleach raw statistics")
    print("=" * 60)

    post_bleach_averages = {}
    post_bleach_sum_averages = {}
    for name in all_names:
        post_bleach_averages[name] = traces_mean[name][BLEACH_CUTOFF_FRAME:].mean()
        post_bleach_sum_averages[name] = traces_sum[name][BLEACH_CUTOFF_FRAME:].mean()

    blac_vals = [post_bleach_averages[n] for n in blac]
    dead_vals = [post_bleach_averages[n] for n in blac_cat_dead]
    blac_sum_vals = [post_bleach_sum_averages[n] for n in blac]
    dead_sum_vals = [post_bleach_sum_averages[n] for n in blac_cat_dead]

    u_stat, p_mann = mannwhitneyu(blac_vals, dead_vals, alternative="two-sided")
    u_stat_sum, p_mann_sum = mannwhitneyu(blac_sum_vals, dead_sum_vals, alternative="two-sided")
    print(f"  Mean: BlaC (n={len(blac)}) {np.mean(blac_vals):.2f} ± {sem(blac_vals):.2f}, "
          f"Dead (n={len(blac_cat_dead)}) {np.mean(dead_vals):.2f} ± {sem(dead_vals):.2f}, "
          f"Mann-Whitney U={u_stat:.1f}, p={p_mann:.4f}")
    print(f"  Sum:  BlaC (n={len(blac)}) {np.mean(blac_sum_vals):.0f} ± {sem(blac_sum_vals):.0f}, "
          f"Dead (n={len(blac_cat_dead)}) {np.mean(dead_sum_vals):.0f} ± {sem(dead_sum_vals):.0f}, "
          f"Mann-Whitney U={u_stat_sum:.1f}, p={p_mann_sum:.4f}")

    stats_rows = []
    for a in ANIMALS:
        stats_rows.append({
            "animal": a["name"],
            "condition": a["condition"],
            "post_bleach_mean_raw": post_bleach_averages[a["name"]],
            "post_bleach_sum_raw": post_bleach_sum_averages[a["name"]],
        })
    stats_df = pd.DataFrame(stats_rows)
    stats_df["mannwhitney_U_mean"] = u_stat
    stats_df["mannwhitney_p_mean"] = p_mann
    stats_df["mannwhitney_U_sum"] = u_stat_sum
    stats_df["mannwhitney_p_sum"] = p_mann_sum
    stats_df["n_blac"] = len(blac)
    stats_df["n_blac_cat_dead"] = len(blac_cat_dead)
    stats_df.to_csv(OUTPUT_DIR / "stats" / "post_bleach_raw_stats.csv", index=False)
    print("  Saved post_bleach_raw_stats.csv")

    def render_dotplot(dead_vals, blac_vals, p_value, ylabel, title, ylim, out_path):
        np.random.seed(42)
        fig, ax = plt.subplots(figsize=(6, 6))
        for v in dead_vals:
            jitter = np.random.uniform(-0.12, 0.12)
            ax.plot(0 + jitter, v, "o", color=COLOR_DEAD, markersize=9, alpha=0.8,
                    markeredgecolor="white", markeredgewidth=0.5)
        for v in blac_vals:
            jitter = np.random.uniform(-0.12, 0.12)
            ax.plot(1 + jitter, v, "o", color=COLOR_ALIVE, markersize=9, alpha=0.8,
                    markeredgecolor="white", markeredgewidth=0.5)
        dead_mean, dead_se = np.mean(dead_vals), sem(dead_vals)
        blac_mean, blac_se = np.mean(blac_vals), sem(blac_vals)
        ax.errorbar(0, dead_mean, yerr=dead_se, color=COLOR_DEAD, fmt="none",
                    elinewidth=2.5, capsize=8, capthick=2.5, zorder=5)
        ax.errorbar(1, blac_mean, yerr=blac_se, color=COLOR_ALIVE, fmt="none",
                    elinewidth=2.5, capsize=8, capthick=2.5, zorder=5)
        ax.hlines(dead_mean, -0.25, 0.25, color=COLOR_DEAD, linewidth=2.5, zorder=6)
        ax.hlines(blac_mean, 0.75, 1.25, color=COLOR_ALIVE, linewidth=2.5, zorder=6)
        ax.set_xticks([0, 1])
        ax.set_xticklabels(["BlaC-Cat.Dead", "BlaC"])
        ax.set_ylabel(ylabel)
        ax.set_title(f"{title} (Mann-Whitney p={p_value:.4f})")
        ax.set_xlim(-0.5, 1.5)
        if ylim is not None:
            ax.set_ylim(ylim)
        plt.tight_layout()
        plt.savefig(out_path, dpi=150, bbox_inches="tight")
        plt.close()

    render_dotplot(dead_vals, blac_vals, p_mann,
                   "Post-bleach avg raw mean intensity",
                   "Post-Bleach Raw Mean Intensity",
                   ylim=(0, 20),
                   out_path=OUTPUT_DIR / "plots" / "dotplot_post_bleach_raw.png")
    print("  Saved dotplot_post_bleach_raw.png")

    render_dotplot(dead_sum_vals, blac_sum_vals, p_mann_sum,
                   "Post-bleach avg raw sum intensity",
                   "Post-Bleach Raw Sum Intensity",
                   ylim=None,
                   out_path=OUTPUT_DIR / "plots" / "dotplot_post_bleach_raw_sum.png")
    print("  Saved dotplot_post_bleach_raw_sum.png")

    print("\n" + "=" * 60)
    print("  DONE!")
    print("=" * 60)
    print(f"  Outputs in: {OUTPUT_DIR}")
